services:

  server1:
    build: .
    container_name: server1
    ports:
      - "2201:22"

  server2:
    build: .
    container_name: server2
    ports:
      - "2202:22"

  server3:
    build: .
    container_name: server3
    ports:
      - "2203:22"

  server4:
    build: .
    container_name: server4
    ports:
      - "2204:22"

  server5:
    build: .
    container_name: server5
    ports:
      - "2205:22"